# GitHub Actions Workflow for launching UI tests on Linux, Windows, and Mac in the following steps:
# - Prepare and launch IDE with your plugin and robot-server plugin, which is needed to interact with the UI.
# - Wait for IDE to start.
# - Run UI tests with a separate Gradle task.
#
# Please check https://github.com/JetBrains/intellij-ui-test-robot for information about UI tests with IntelliJ Platform.
#
# Workflow is triggered manually.

name: Run UI Tests
on:
  workflow_dispatch

jobs:

  testUI:
    runs-on: ${{ matrix.os }}
    env:
      MODULE: ${{ matrix.module }}
    strategy:
      fail-fast: false
      matrix:
        module: [":plugins:template"]
        include:
          - os: ubuntu-latest
            runIde: |
              export DISPLAY=:99.0
              Xvfb -ac :99 -screen 0 1920x1080x16 &
              ./gradlew "$MODULE:runIdeForUiTests" &
          - os: windows-latest
            runIde: Start-Process -FilePath .\gradlew.bat -ArgumentList "$(($env:MODULE)):runIdeForUiTests"
          - os: macos-latest
            runIde: ./gradlew "$MODULE:runIdeForUiTests" &

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Run IDE
        run: ${{ matrix.runIde }}

      - name: Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://127.0.0.1:8082
          max-attempts: 15
          retry-delay: 30s

      - name: Tests
        run: ./gradlew "$MODULE:test"
